name: Typescript Checks

on:
  workflow_call:

jobs:
  check_typescript:
    name: Check Typescript library
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Typescript"
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm ci
          npm audit --audit-level critical
        working-directory: ./src/typescript

      - name: Build
        run: npm run build
        working-directory: ./src/typescript

      - name: Test
        run: npm test
        working-directory: ./src/typescript

      - name: Lint
        run: npm run lint
        working-directory: ./src/typescript

  check_typescript_chatbot:
    name: Check Typescript chatbot
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Typescript"
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Build and link local package
        run: |
          npm ci
          npm audit --audit-level critical
          npm run build
          npm link
        working-directory: ./src/typescript

      - name: Install dependencies
        run: |
          npm ci
          npm audit --audit-level critical
          npm link @aws/run-mcp-servers-with-aws-lambda
        working-directory: ./examples/chatbots/typescript

      - name: Build
        run: npm run build
        working-directory: ./examples/chatbots/typescript

  check_typescript_e2e_tests:
    name: Check Typescript E2E tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Typescript"
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Build and link local package
        run: |
          npm ci
          npm audit --audit-level critical
          npm run build
          npm link
        working-directory: ./src/typescript

      - name: Install dependencies
        run: |
          npm ci
          npm audit --audit-level critical
          npm link @aws/run-mcp-servers-with-aws-lambda
        working-directory: ./e2e_tests/typescript

      - name: Build
        run: npm run build
        working-directory: ./e2e_tests/typescript
